name: Frosti Provision and Deploy 

on: 
  push:
    branches:
      - 'main'
      - 'master'
  workflow_dispatch:

jobs:
  InfraProvision:
    runs-on: macos-latest
    outputs:
        WEB_APP_NAME: ${{ steps.run-frosti.outputs.WEB_APP_NAME }}
        FUNCTION_APP_NAME: ${{ steps.run-frosti.outputs.FUNCTION_APP_NAME }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run Frosti
        id: run-frosti
        run: |
            az --version
            az account show
            brew update
            brew install CirroBuild/tap/frosti
            myAppNames=`frosti provision -s 8850fa2d-2fec-446e-81ce-0866bd59fc04 -r github -e ppe | grep -E 'WebAppName|FunctionAppName'`
            echo $myAppNames
            myWebApp=`echo $myAppNames | grep WebAppName | sed -e 's/WebAppName://g'`
            myFunctionApp=`echo $myAppNames | grep FunctionAppName | sed -e 's/FunctionAppName://g'`
            echo "WEB_APP_NAME=$myWebApp" >> $GITHUB_OUTPUT
            echo "FUNCTION_APP_NAME=$myFunctionApp" >> $GITHUB_OUTPUT
            
      - name: Display
        run: echo "${{ steps.run-frosti.outputs.FUNCTION_APP_NAME }}"
            
  BuildProject:
    runs-on: macos-latest
    needs: [infraProvision]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.0.x
            7.0.x
        
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build CascadeBrewingCo.csproj --configuration Release --no-restore
      
      - name: Test
        run: dotnet test CascadeBrewingCo.csproj --no-restore --verbosity normal
        
      - name: Publish
        run: dotnet publish CascadeBrewingCo.csproj -c Release --output ./release
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure Web Deploy
        if: needs.infraProvision.outputs.WEB_APP_NAME != null && needs.infraProvision.outputs.WEB_APP_NAME != ''
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ needs.infraProvision.outputs.WEB_APP_NAME }}
          package: ./release
          
      - name: Azure Function Deploy
        if: needs.infraProvision.outputs.FUNCTION_APP_NAME != null && needs.infraProvision.outputs.FUNCTION_APP_NAME != ''
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ needs.infraProvision.outputs.FUNCTION_APP_NAME }}
          package: ./release
      
      - name: logout
        run: |
          az logout 